[package]
name = "riscv-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
bril-frontend = { path = "../bril-frontend" }
bril-ir = { path = "../bril-ir" }
bril-passes = { path = "../bril-passes" }
