extract = 'total_dyn_inst: (\d+)'
benchmarks = '../benchmarks/core/*.bril'
timeout = 30

[runs.baseline]
pipeline = ["bril2json", "python tdce.py tdce+", "brili -p {args}"]

[runs.crude-ssa]
pipeline = [
    "bril2json",
    "python tdce.py tdce+",
    "python to_ssa_crude.py",
    "python tdce.py tdce+",
    "brili -p {args}",
]

[runs.crude-roundtrip]
pipeline = [
    "bril2json",
    "python tdce.py tdce+",
    "python to_ssa_crude.py",
    "python tdce.py tdce+",
    "python from_ssa.py",
    "python tdce.py tdce+",
    "brili -p {args}",
]

[runs.full-ssa]
pipeline = [
    "bril2json",
    "python tdce.py tdce+",
    "python to_ssa.py",
    "python tdce.py tdce+",
    "brili -p {args}",
]

[runs.full-roundtrip]
pipeline = [
    "bril2json",
    "python tdce.py tdce+",
    "python to_ssa.py",
    "python tdce.py tdce+",
    "python from_ssa.py",
    "python tdce.py tdce+",
    "brili -p {args}",
]
