[package]
name = "bril2json"
description = "Convert textual Bril to JSON"
authors = ["Ethan Uppal"]
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT"

[dependencies]
bril-frontend = "0.2.2"
annotate-snippets = "0.11.5"
snafu = "0.8.5"
argh = "0.1.13"
serde_json = "1.0.138"
